apt-get install fail2ban -y --fix-missing;
mkdir .ssh;
chmod 700 .ssh;
sed -i "s/.*#PasswordAuthentication yes/PasswordAuthentication no/g" "/etc/ssh/sshd_config";
sed -i "s/.*#PermitEmptyPasswords no/PermitEmptyPasswords no/g" "/etc/ssh/sshd_config";
sed -i "s/.*UsePAM yes/UsePAM no/g" "/etc/ssh/sshd_config";
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA2xTYcuWeJqxPqzwpjorMrq0pl3iN2eWMYOa5h5/NPfypXBxYYHo0aB+zMucplPtWVixyn8b6B+HuqeJrEws7MWJ0ReUbWRwcqt9R9oQU3i9dkXrOwF7jopQZ6GiIc0fNBvkuMeEhlGiePA3rVFtbx4NrAzdqv9mDerORfd6tJNyw1sWzWHj1scFo973JyC7vBGy4HPygIPevEW1j21/H5yZW/9DYphdN8RTvSjSxILcu/2pdM9CH9STP8RjY/UDgK2C6PoXT1k34z2moPjsDNCnjRZoHWH+hJisaGXV9qPju+XcYtKOvLSNNP7yoALgRxkjK7K9srDa88Diy1RNuVQ== rsa-key-dev" >> $HOME/.ssh/authorized_keys;
systemctl restart sshd.service;
sed -i "s/^\[sshd\]/\[sshd\]\nenabled = true\nbantime = 86400\nfindtime = 60m\nmaxretry = 1\nbanaction = iptables-multiport\n/g" "/etc/fail2ban/jail.conf";
sed -i "s/^disable_functions \= /disable_function \= mail,/g" "/etc/php/7.3/fpm/php.ini";
sed -i "s/^disable_functions \= /disable_function \= mail,/g" "/etc/php/7.4/fpm/php.ini";
systemctl enable fail2ban;
systemctl restart php7.3-fpm;
systemctl restart php7.4-fpm;
systemctl restart fail2ban;
rm up.sh;
